<a href="https://colab.research.google.com/github/hiranya15/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment No. 8
#Tools for EDA - Study of Numpy Library
#Hiranya
#25070123054
#ENCT A3


#NumPy

In [1]:
#Declaration of NumPy
import numpy as np

a=np.array([10,20,30,40])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print()
print(b)

[10 20 30 40]

[[1 2 3]
 [4 5 6]]


In [2]:
#Dimension of Array

print(a.ndim)
print(b.ndim)


1
2


In [3]:
a.shape


(4,)

In [4]:
b.shape


(2, 3)

In [5]:
a.dtype

dtype('int64')

In [6]:
#inbuilt functions using numpy
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
print(b*2)
print(a+5)


[[ 2  4  6]
 [ 8 10 12]]
[15 25 35 45]


In [13]:
np.mean(a)


np.float64(25.0)

In [16]:
np.mean(b)


np.float64(3.5)

In [14]:
np.median(a)

np.float64(25.0)

In [17]:
np.median(b)


np.float64(3.5)

In [15]:
np.max(a)


np.int64(40)

In [18]:
np.max(b)



np.int64(6)

In [19]:
np.sum(a)

np.int64(100)

In [20]:
np.sum(b)


np.int64(21)